### ISSUE TITLE
seminars not sorted correctly by date

### ISSUE THREAD

**Issue by mehrhardt** [mathematics-and-algorithms-for-data/mathematics-and-algorithms-for-data.github.io#1]
The seminars are sorted by time instead of date. E.g. for
1. Time: 14:15, 21 Mar, 2019
2. Time: 13:15, 26 Nov, 2019

then 1) is "after" 2) in lexicographic ordering because of the time of the day.

**Comment by ndfcampbell** [comment]
Sorry - my fault. In the YAML file the date needs to be entered in ISO format so like this:

2019-11-26 13:15

year-month-day hour:min

Then everything should sort in reverse date order correctly.
